#!/bin/sh
set -e

case "$1" in
    configure)
        update-alternatives --install /usr/bin/amarelo-mind amarelo-mind /usr/share/amarelo-mind/AmareloMind 100 2>/dev/null || true
        ;;
esac

exit 0